### ISSUE TITLE
Running setup.py install for cchardet ... error

### ISSUE THREAD

**Issue by PrevotYann** [DrankRock/CMScrape#3]
Lors de l'install : 

`Running setup.py install for cchardet ... error
  error: subprocess-exited-with-error

  × Running setup.py install for cchardet did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      C:\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\version.py -> build\lib.win-amd64-cpython-311\cchardet
      copying src\cchardet\__init__.py -> build\lib.win-amd64-cpython-311\cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cchardet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

Lorsque j'essaie de run : 

`CMScrape>python CMScrape.py
Traceback (most recent call last):
  File "C:\Users\XXXXX\Documents\CMScrape\CMScrape.py", line 18, in <module>
    from multiProcess import *
  File "C:\Users\XXXXX\Documents\CMScrape\multiProcess.py", line 10, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'`

Même problème sur Windows et Mac, testé avec Python 3.11 sur Windows et 3.10 sur MacOs

**Comment by DrankRock** [comment]
Hello!
I will look into this, but please note that cmscrape is currently broken due to the adding of cloudflare security on the cardmarket website. A newer yet different version is in my mind but I'm not sure how it will work out in the end. I'm also working on some shenanigans to make the use in windows easier.

Thank you for the issue report!

Have a nice day
